name: Build and Deploy
run-name: ${{ github.event.head_commit.message }}
on:
  release:
    types: [published]

jobs:
  build:
    name: Build it!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run:  npm install
      
      - name: Build
        run:  npm run build --mode=production
      
      - name: Check output
        run:  cd dist/ && ls
      
      - name: Check release version
        run:  echo "This is release ${{ github.event.release.tag_name }}"