name: Build and Deploy
run-name: Deploy [${{ github.event.head_commit.message }}]
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build it!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Test message
        run: echo "Hello from the GH action"