name: Build and Deploy
run-name: ${{ github.event.release.tag_name }} ${{ github.event.release.name }}
on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      NAME: yourstake-embed-sdk
      VER:  ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run:  npm install
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Build for production
        run:  npm run build --mode=production
      
      - name: Copy production files to S3
        run: |
          aws s3 cp dist/${NAME}.js s3://stake-assets/embed/${NAME}-${VER}.js --acl public-read
          aws s3 cp dist/${NAME}.js s3://stake-assets/embed/${NAME}-latest.js --acl public-read
      
      - name: Build for staging
        run:  npm run build --mode=staging
      
      - name: Copy staging files to S3
        run: |
          aws s3 cp dist/${NAME}.js s3://stake-assets/embed/staging/${NAME}-${VER}.js --acl public-read
          aws s3 cp dist/${NAME}.js s3://stake-assets/embed/staging/${NAME}-latest.js --acl public-read
      
      - name: Check results
        run:  aws s3 ls s3://stake-assets/embed/