name: Build and Deploy
run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches: main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run:  npm install
      
      - name: Build
        run:  npm run build --mode=production
      
      - name: Check output
        run:  cd dist/ && ls
      
      - name: Check release version
        run:  echo "This is release ${{ github.event.release.tag_name }}"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Copy file to S3
        run:  aws s3 cp dist/yourstake-embed-sdk.js s3://stake-assets/embed/ --acl public-read
      
      - name: Check results
        run:  aws s3 ls s3://stake-assets/embed/